import type { Metadata } from "next";
import { Karla } from "next/font/google";
import "./globals.css";
import Header from "./components/header";
import "../../tailwind-preserve-classes";

const karla = Karla({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Pokedex",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${karla.className} antialiased w-full h-screen`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
